name: wildscout
description: Your offline AI companion for exploring nature safely.
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  image_picker: ^1.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/sample_analyze_response.json
    - assets/forest.jpg
    - assets/fern.jpg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/Inter.ttf
    - family: Jakarta
      fonts:
        - asset: assets/Jakarta.ttf
